@ECHO OFF
SETLOCAL

ECHO. Deleting temporary Ninite for Windows 7 installation files...
DEL %USERPROFILE%\Downloads\Ninite7.exe
ECHO. Deleting temporary Ninite for Windows 8 installation files...
DEL %USERPROFILE%\Downloads\Ninite8.exe
ECHO. Deleting temporary Ninite for Windows 10 installation files...
DEL %USERPROFILE%\Downloads\Ninite10.exe
ECHO. Deleting temporary CCleaner installation files...
DEL %USERPROFILE%\Downloads\ccsetup520.exe
ECHO. Deleting temporary Avast installation files...
DEL %USERPROFILE%\Downloads\avast_free_antivirus_setup_online_cnet_2.exe
ECHO. Deleting temporary ESET NOD32 Anti-Virus installation files...
DEL %USERPROFILE%\Downloads\eset_nod32_antivirus_live_installer.exe
ECHO. Deleting temporary Junkware Removal Tool installation files...
DEL %USERPROFILE%\Downloads\JRT.exe
ECHO. Deleting temporary Auslogics Disk Defrag installation files...
DEL %USERPROFILE%\Downloads\disk-defrag-setup.exe
ECHO. Deleting temporary Flash Player installation files...
DEL %USERPROFILE%\Downloads\flashplayer22_xa_install.exe
ECHO. Deleting temporary Acrobat Reader installation files...
DEL %USERPROFILE%\Downloads\readerdc_en_xa_install.exe
ECHO. Deleting temporary Never10 installation files...
DEL %USERPROFILE%\Downloads\never10.exe
ECHO. Deleting temporary Adblock Plus for Internet Explorer installation files...
DEL %USERPROFILE%\Downloads\adblockplusie.exe

GOTO:EOF